spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/study/inflearn_spring_jpa/h2/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
